name: Test Backend
on: [push, pull_request]

jobs:
  backend-build:

    runs-on: ubuntu-latest

    ganache:
        image: trufflesuite/ganache-cli
        ports:
          - 8545:8545

    mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
        ports:
          - 27017:27017

    steps: 
      - name: Clone repo
        uses: actions/checkout@v2
      
      - name: Setup node (If running in Github Actions)
        if: ${{ !env.ACT }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Setup node (If running locally via act)
        if: ${{ env.ACT }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./backend
        run: npm install
      
      - name: Run tests
        working-directory: ./backend
        run: npm test